# 25.08.15
# https://repo.maven.apache.org/maven2/org/jetbrains/
# https://maven.google.com/web/index.html#androidx.compose
# ./gradlew compose:dependencies --configuration allSourceSetsCompileDependenciesMetadata > report.txt

[versions]
### KMP
# https://github.com/JetBrains/compose-multiplatform
compose-material3 = "1.9.0-beta03" # based: 1.4.0-beta01 # https://developer.android.com/jetpack/androidx/releases/compose-material3
compose-material3-adaptive = "1.2.0-alpha05" # based: 1.2.0-alpha10 # https://developer.android.com/jetpack/androidx/releases/compose-material3-adaptive
compose-graphics = "1.0.0-alpha09" # based: 1.0.1 # https://developer.android.com/jetpack/androidx/releases/graphics
compose-lifecycle = "2.9.2" # based: 2.9.2 # https://developer.android.com/jetpack/androidx/releases/lifecycle
compose-navigation = "2.9.0-beta05" # based: 2.9.2 # https://developer.android.com/jetpack/androidx/releases/navigation
compose-savedstate = "1.3.2" # based: 1.3.1 # https://developer.android.com/jetpack/androidx/releases/savedstate
compose-window = "1.4.0-beta01" # based: 1.4.0 # https://developer.android.com/jetpack/androidx/releases/window
compose-haze = "1.6.9" # https://github.com/chrisbanes/haze
molecule = "2.1.0" # https://github.com/cashapp/molecule
kotlinx-datetime = "0.7.1" # https://github.com/Kotlin/kotlinx-datetime
kotlinx-serialization = "1.9.0" # https://github.com/Kotlin/kotlinx.serialization
kotlinx-collections-immutable = "0.4.0" # https://github.com/Kotlin/kotlinx.collections.immutable
datastore = "1.1.7" # https://developer.android.com/jetpack/androidx/releases/datastore
ktor = "3.2.3" # https://github.com/ktorio/ktor
coil = "3.3.0" # https://github.com/coil-kt/coil
sketch = "4.4.0-alpha01" # https://github.com/panpf/sketch
crashkios = "0.9.0" # https://github.com/touchlab/CrashKiOS
kermit = "2.0.5" # https://github.com/touchlab/Kermit
nsexceptionkt = "1.0.2" # https://github.com/rickclephas/NSExceptionKt
### Android
# https://github.com/androidx/androidx
# https://developer.android.com/jetpack/androidx/versions
androidx-core = "1.17.0" # https://developer.android.com/jetpack/androidx/releases/core
androidx-activity = "1.10.1" # https://developer.android.com/jetpack/androidx/releases/activity
androidx-media3 = "1.8.0" # https://developer.android.com/jetpack/androidx/releases/media3
### iOS
### Others


[libraries]
### KMP
compose-material3 = { group = "org.jetbrains.compose.material3", name = "material3", version.ref = "compose-material3" }
compose-material3-adaptive-navigation-suite = { group = "org.jetbrains.compose.material3", name = "material3-adaptive-navigation-suite", version.ref = "compose-material3" }
compose-material3-adaptive = { group = "org.jetbrains.compose.material3.adaptive", name = "adaptive", version.ref = "compose-material3-adaptive" }
compose-material3-adaptive-layout = { group = "org.jetbrains.compose.material3.adaptive", name = "adaptive-layout", version.ref = "compose-material3-adaptive" }
compose-material3-adaptive-navigation = { group = "org.jetbrains.compose.material3.adaptive", name = "adaptive-navigation", version.ref = "compose-material3-adaptive" }
compose-graphics = { group = "org.jetbrains.androidx.graphics", name = "graphics-shapes", version.ref = "compose-graphics" }
compose-lifecycle = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "compose-lifecycle" }
compose-lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "compose-lifecycle" }
compose-lifecycle-viewmodel-savedstate = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel-savedstate", version.ref = "compose-lifecycle" }
compose-navigation = { group = "org.jetbrains.androidx.navigation", name = "navigation-compose", version.ref = "compose-navigation" }
compose-savedstate = { group = "org.jetbrains.androidx.savedstate", name = "savedstate-compose", version.ref = "compose-savedstate" }
compose-window = { group = "org.jetbrains.androidx.window", name = "window-core", version.ref = "compose-window" }
compose-haze = { group = "dev.chrisbanes.haze", name = "haze", version.ref = "compose-haze" }
compose-haze-materials = { group = "dev.chrisbanes.haze", name = "haze-materials", version.ref = "compose-haze" }
molecule = { group = "app.cash.molecule", name = "molecule-runtime", version.ref = "molecule" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-serialization-protobuf = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-protobuf", version.ref = "kotlinx-serialization" }
kotlinx-serialization-cbor = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-cbor", version.ref = "kotlinx-serialization" }
kotlinx-collections-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinx-collections-immutable" }
datastore = { group = "androidx.datastore", name = "datastore-core", version.ref = "datastore" }
datastore-okio = { group = "androidx.datastore", name = "datastore-core-okio", version.ref = "datastore" }
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences-core", version.ref = "datastore" }
ktor-bom = { group = "io.ktor", name = "ktor-bom", version.ref = "ktor" }
ktor-client-core = { group = "io.ktor", name = "ktor-client-core" }
ktor-client-cio = { group = "io.ktor", name = "ktor-client-cio" }
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp" }
ktor-client-android = { group = "io.ktor", name = "ktor-client-android" }
ktor-client-drawain = { group = "io.ktor", name = "ktor-client-darwin" }
ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation" }
ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json" }
ktor-serialization-kotlinx-protobuf = { group = "io.ktor", name = "ktor-serialization-kotlinx-protobuf" }
ktor-serialization-kotlinx-cbor = { group = "io.ktor", name = "ktor-serialization-kotlinx-cbor" }
ktor-server-core = { group = "io.ktor", name = "ktor-server-core-jvm" }
ktor-server-netty = { group = "io.ktor", name = "ktor-server-netty-jvm" }
ktor-server-tests = { group = "io.ktor", name = "ktor-server-tests-jvm" }
coil-bom = { group = "io.coil-kt.coil3", name = "coil-bom", version.ref = "coil" }
coil = { group = "io.coil-kt.coil3", name = "coil" }
coil-core = { group = "io.coil-kt.coil3", name = "coil-core" }
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose" }
coil-compose-core = { group = "io.coil-kt.coil3", name = "coil-compose-core" }
coil-network-cache-control = { group = "io.coil-kt.coil3", name = "coil-network-cache-control" }
coil-network-ktor3 = { group = "io.coil-kt.coil3", name = "coil-network-ktor3" }
coil-svg = { group = "io.coil-kt.coil3", name = "coil-svg" }
coil-gif = { group = "io.coil-kt.coil3", name = "coil-gif" }
coil-video = { group = "io.coil-kt.coil3", name = "coil-video" }
coil-test = { group = "io.coil-kt.coil3", name = "coil-test" }
sketch = { group = "io.github.panpf.sketch4", name = "sketch-singleton", version.ref = "sketch" }
sketch-compose = { group = "io.github.panpf.sketch4", name = "sketch-compose", version.ref = "sketch" }
sketch-compose-extensions = { group = "io.github.panpf.sketch4", name = "sketch-extensions-compose", version.ref = "sketch" }
sketch-compose-resources = { group = "io.github.panpf.sketch4", name = "sketch-extensions-compose-resources", version.ref = "sketch" }
sketch-http-ktor3 = { group = "io.github.panpf.sketch4", name = "sketch-http-ktor3", version.ref = "sketch" }
sketch-blurhash = { group = "io.github.panpf.sketch4", name = "sketch-blurhash", version.ref = "sketch" }
sketch-svg = { group = "io.github.panpf.sketch4", name = "sketch-svg", version.ref = "sketch" }
sketch-gif = { group = "io.github.panpf.sketch4", name = "sketch-animated-gif", version.ref = "sketch" }
sketch-webp = { group = "io.github.panpf.sketch4", name = "sketch-animated-webp", version.ref = "sketch" }
sketch-video-android = { group = "io.github.panpf.sketch4", name = "sketch-video", version.ref = "sketch" }
sketch-video-ffmpeg-android = { group = "io.github.panpf.sketch4", name = "sketch-video-ffmpeg", version.ref = "sketch" }
### Android
androidx-core = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
androidx-activity = { group = "androidx.activity", name = "activity-ktx", version.ref = "androidx-activity" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity" }
# + media3 - https://developer.android.com/jetpack/androidx/releases/media3
androidx-media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "androidx-media3" }
androidx-media3-exoplayer-dash = { group = "androidx.media3", name = "media3-exoplayer-dash", version.ref = "androidx-media3" }
androidx-media3-exoplayer-hls = { group = "androidx.media3", name = "media3-exoplayer-hls", version.ref = "androidx-media3" }
androidx-media3-exoplayer-smoothstreaming = { group = "androidx.media3", name = "media3-exoplayer-smoothstreaming", version.ref = "androidx-media3" }
androidx-media3-exoplayer-rtsp = { group = "androidx.media3", name = "media3-exoplayer-rtsp", version.ref = "androidx-media3" }
androidx-media3-exoplayer-midi = { group = "androidx.media3", name = "media3-exoplayer-midi", version.ref = "androidx-media3" }
androidx-media3-exoplayer-ima = { group = "androidx.media3", name = "media3-exoplayer-ima", version.ref = "androidx-media3" }
androidx-media3-datasource-cronet = { group = "androidx.media3", name = "media3-datasource-cronet", version.ref = "androidx-media3" }
androidx-media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "androidx-media3" }
androidx-media3-ui-compose = { group = "androidx.media3", name = "media3-ui-compose", version.ref = "androidx-media3" }
androidx-media3-ui-leanback = { group = "androidx.media3", name = "media3-ui-leanback", version.ref = "androidx-media3" }
androidx-media3-session = { group = "androidx.media3", name = "media3-session", version.ref = "androidx-media3" }
androidx-media3-extractor = { group = "androidx.media3", name = "media3-extractor", version.ref = "androidx-media3" }
androidx-media3-cast = { group = "androidx.media3", name = "media3-cast", version.ref = "androidx-media3" }
androidx-media3-exoplayer-workmanager = { group = "androidx.media3", name = "media3-exoplayer-workmanager", version.ref = "androidx-media3" }
androidx-media3-transformer = { group = "androidx.media3", name = "media3-transformer", version.ref = "androidx-media3" }
androidx-media3-effect = { group = "androidx-media3", name = "media3-effect", version.ref = "androidx-media3" }
androidx-media3-muxer = { group = "androidx-media3", name = "media3-muxer", version.ref = "androidx-media3" }
androidx-media3-test-utils = { group = "androidx-media3", name = "media3-test-utils", version.ref = "androidx-media3" }
androidx-media3-test-utils-robolectric = { group = "androidx-media3", name = "media3-test-utils-robolectric", version.ref = "androidx-media3" }
androidx-media3-container = { group = "androidx-media3", name = "media3-container", version.ref = "androidx-media3" }
androidx-media3-database = { group = "androidx-media3", name = "media3-database", version.ref = "androidx-media3" }
androidx-media3-decoder = { group = "androidx-media3", name = "media3-decoder", version.ref = "androidx-media3" }
androidx-media3-datasource = { group = "androidx-media3", name = "media3-datasource", version.ref = "androidx-media3" }
androidx-media3-common = { group = "androidx-media3", name = "media3-common", version.ref = "androidx-media3" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth" }
firebase-cloud-messaging = { group = "com.google.firebase", name = "firebase-messaging" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }
firebase-crashlytics-ndk = { group = "com.google.firebase", name = "firebase-crashlytics-ndk" }
firebase-performance = { group = "com.google.firebase", name = "firebase-perf" }
### iOS
nsexceptionkt-core = { group = "com.rickclephas.kmp", name = "nsexception-kt-core", version.ref = "nsexceptionkt" }
nsexceptionkt-crashlytics = { group = "com.rickclephas.kmp", name = "nsexception-kt-crashlytics", version.ref = "nsexceptionkt" }
### Others


[bundles]
### KMP
compose = [
    "compose-material3", "compose-material3-adaptive-navigation-suite",
    "compose-material3-adaptive", "compose-material3-adaptive-layout", "compose-material3-adaptive-navigation",
    "compose-lifecycle", "compose-lifecycle-viewmodel", "compose-lifecycle-viewmodel-savedstate",
    "compose-navigation",
    "compose-savedstate",
    "compose-window",
    #
    "compose-haze", "compose-haze-materials",
]
kotlinx = [
    "kotlinx-datetime",
    "kotlinx-collections-immutable",
]
datastore = ["datastore", "datastore-okio", "datastore-preferences"]
ktor = [
    "ktor-client-core",
    "ktor-client-content-negotiation", "ktor-serialization-kotlinx-json", "ktor-serialization-kotlinx-protobuf",
    "ktor-client-logging",
]
ktor-android = [
    "ktor-client-okhttp",
]
ktor-ios = [
    "ktor-client-drawain",
]
coil = [
    "coil",
    "coil-network-cache-control", "coil-network-ktor3",
]
coil-compose = [
    "coil-compose",
    "coil-network-cache-control", "coil-network-ktor3",
]
sketch = [
    "sketch",
    "sketch-http-ktor3",
    "sketch-blurhash",
]
sketch-compose = [
    "sketch-compose", "sketch-compose-extensions", "sketch-compose-resources",
    "sketch-http-ktor3",
    "sketch-blurhash",
]
### Android
androidx-compose = [
    "androidx-activity-compose",
]
androidx-media = [
    "androidx-media3-exoplayer",
]
androidx-media-ui = [
    "androidx-media3-ui-compose",
]
firebase-crashlytics = ["firebase-crashlytics", "firebase-crashlytics-ndk"]
### iOS
nsexceptionkt = [
    "nsexceptionkt-core"
]
### Others


[plugins]

