# 25.08.15

[versions]
### KMP
crestfi-kmp-shared = "0.1.1" # https://github.com/ib-fi/kmp-shared
# maven { url = uri("https://maven.pkg.jetbrains.space/public/p/compose/dev") }
# https://github.com/JetBrains/compose-multiplatform-core/blob/jb-main/gradle.properties
# https://maven.pkg.jetbrains.space/public/p/compose/dev/org/jetbrains/compose/material3/material3/
material3-kmp = "1.9.10+dev2792" # 1.5.0-alpha01
### Android
# https://developer.android.com/jetpack/androidx/releases/compose-material3
# https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/material3/material3/samples/src/main/java/androidx/compose/material3/samples/
material3-android = "1.5.0-alpha02"
amplitude = "1.22.0" # https://github.com/amplitude/Amplitude-Kotlin
facebook = "18.1.3" # https://github.com/facebook/facebook-android-sdk
appsFlyer = "6.17.2" # https://github.com/AppsFlyerSDK/appsflyer-android-sdk
### iOS
crashkios = "0.9.0" # https://github.com/touchlab/CrashKiOS
kermit = "2.0.5" # https://github.com/touchlab/Kermit
nsexceptionkt = "1.0.2" # https://github.com/rickclephas/NSExceptionKt
### Others


[libraries]
### KMP
crestfi-kmp-shared = { group = "pro.crestfi.kmp", name = "shared", version.ref = "crestfi-kmp-shared" }
crestfi-kmp-compose = { group = "pro.crestfi.kmp", name = "compose", version.ref = "crestfi-kmp-shared" }
material3-kmp= { group = "org.jetbrains.compose.material3", name = "material3", version.ref = "material3-kmp" }
material3-kmp-window-size = { group = "org.jetbrains.compose.material3", name = "material3-window-size-class", version.ref = "material3-kmp" }
material3-kmp-adaptive-navigation-suite = { group = "org.jetbrains.compose.material3", name = "material3-adaptive-navigation-suite", version.ref = "material3-kmp" }
material3-android = { group = "androidx.compose.material3", name = "material3", version.ref = "material3-android" }
material3-android-window-size = { group = "androidx.compose.material3", name = "material3-window-size-class", version.ref = "material3-android" }
material3-android-adaptive-navigation-suite = { group = "androidx.compose.material3", name = "material3-adaptive-navigation-suite", version.ref = "material3-android" }
### Android
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth" }
firebase-cloud-messaging = { group = "com.google.firebase", name = "firebase-messaging" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }
firebase-crashlytics-ndk = { group = "com.google.firebase", name = "firebase-crashlytics-ndk" }
firebase-performance = { group = "com.google.firebase", name = "firebase-perf" }
amplitude = { group = "com.amplitude", name = "analytics-android", version.ref = "amplitude" }
facebook = { group = "com.facebook.android", name = "facebook-core", version.ref = "facebook" }
appsFlyer = { group = "com.appsflyer", name = "af-android-sdk", version.ref = "appsFlyer" }
### iOS
nsexceptionkt-core = { group = "com.rickclephas.kmp", name = "nsexception-kt-core", version.ref = "nsexceptionkt" }
nsexceptionkt-crashlytics = { group = "com.rickclephas.kmp", name = "nsexception-kt-crashlytics", version.ref = "nsexceptionkt" }
### Others


[bundles]
### KMP
material3-kmp = [
    "material3-kmp",
    "material3-kmp-window-size",
    "material3-kmp-adaptive-navigation-suite",
]
### Android
material3-android = [
    "material3-android",
    "material3-android-window-size",
    "material3-android-adaptive-navigation-suite",
]
firebase-crashlytics = ["firebase-crashlytics", "firebase-crashlytics-ndk"]
### iOS
nsexceptionkt = ["nsexceptionkt-core"]
### Others


[plugins]
### KMP
### Android
### iOS
### Others

